### ISSUE TITLE
No contacts in contact list

### ISSUE THREAD

**Issue by cristinasitaa** [chat21/chat21-ios-demo#2]
I successfully ran the demo project on my device and a simulator, signed up with 2 different accounts, but the contact list from the app remains empty. Can you help me with this? 
Thanks

**Comment by sponzillo** [comment]
Hi Cristina, did you installed "Firebase Cloud functions" on your Firebase project? (it's the point 5 of the Build & Run paragraph)
They are available in this repo:

https://github.com/chat21/chat21-cloud-functions
