### ISSUE TITLE
I'm getting some build errors when I try to build

### ISSUE THREAD

**Issue by islamanwar** [chat21/chat21-ios-demo#3]
https://prnt.sc/ksdknd

**Comment by sponzillo** [comment]
Download Tiledesk libs (the live chat used to ask for support) from this repo:

https://github.com/Tiledesk/tiledesk-ios-sdk

Then drag and drop the TiledeskWidget folder to Xcode project like in the following picture:

<img width="912" alt="screen_chat21_demo_tiledesk_dragdrop" src="https://user-images.githubusercontent.com/32564846/45289998-c7141b80-b4ee-11e8-96fd-2d73708d644c.png">

Now the project will build correctly.

The tutorial will be uploaded soon with this update.

**Comment by islamanwar** [comment]
Thank you!
