### ISSUE TITLE
Do you have any plans to make this library in swift ?

### ISSUE THREAD

**Issue by islamanwar** [chat21/chat21-ios-demo#4]

**Comment by sponzillo** [comment]
Yes, a complete translation (re-design) in Swift is in progress. Meanwhile we are developing a Objc-Swift bridge to espose the most important API and permitting an easy integration in Swift projects. Documentation (Objc and Swift) is coming soon on the chat21.org site.

**Comment by islamanwar** [comment]
Thank you. Thats nice to hear. Do you have any time expectations as to when that could be available ?

**Comment by sponzillo** [comment]
For the end of October we'll release chat21 swift bridge library.
